import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GiDuck } from "react-icons/gi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Nex13 e-commerce",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<section className="sm-py-10 mx-auto max-w-md p-12 sm:max-w-2xl sm:py-16 md:max-w-4xl lg:max-w-7xl">
					{children}
				</section>
				<footer className="text-center text-sm text-gray-800">
					<p>
						© The Rock Shop
						<span id="year"> {new Date().getFullYear()}</span>
					</p>
					<p>
						All Rights Reserved |
						<span className="text-blue-600">
							{" "}
							Blue Duck Dev <GiDuck className="inline scale-x-[-1]" />
						</span>
					</p>
				</footer>
			</body>
		</html>
	);
}
